name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-size: 20

      - name: Install Shopware CLI
        uses: shopware/shopware-cli-action@v3

      - name: Build and package LocalProductOptPlugin
        uses: shopware/build-extension-zip-action@v1
        with:
          extension-path: 'LocalProductOptPlugin'

      - name: Upload production ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: LocalProductOptPlugin-Release
          path: LocalProductOptPlugin*.zip
